### ISSUE TITLE
SCHED0021 fails on star64 platform when config `LibUtilsDefaultZfLogLevel` is `0`

### ISSUE THREAD

**Issue by canarysnort01** [seL4/sel4test#109]
I suspect the extra debug prints might be causing the timing measurements to be off.

I'm testing this on the pinetab-v hardware as described in https://github.com/seL4/seL4/pull/1019#issuecomment-1686518507.

When building sel4test like this, all is well in the universe:

```bash
../init-build.sh -DPLATFORM=star64 -DKernelRiscvExtD=true -DUseRiscVOpenSBI=false -DSIMULATION=false -DMCS=true -DSMP=false
```

Output: [sel4test-star64-mcs.txt](https://github.com/seL4/sel4test/files/13326218/sel4test-star64-mcs.txt)

However, when built with verbose logging, SCHED0021 fails:

```bash
../init-build.sh -DPLATFORM=star64 -DKernelRiscvExtD=true -DUseRiscVOpenSBI=false -DSIMULATION=false -DMCS=true -DSMP=false -DLibUtilsDefaultZfLogLevel=0
```
Output: [sel4test-star64-mcs-verbose.txt](https://github.com/seL4/sel4test/files/13326220/sel4test-star64-mcs-verbose.txt)

**Comment by Indanz** [comment]
The `ZF_LOGD("Releasing Threads");` should be before the `uint64_t start = time_now(env);` and there should be another yield call before `test_simple_preempt_start = 1;` too.

And I'd remove the `ZF_LOGD` in `test_simple_preempt_runner()` too, as it's not shown anyway I think and doesn't add anything anyway.

**Comment by canarysnort01** [comment]
Oh, some of these changes have already been made recently, sorry for the confusion. I will make the remaining changes.

**Comment by canarysnort01** [comment]
> * The `ZF_LOGD("Releasing Threads");` should be before the `uint64_t start = time_now(env);`.
> 
> * There should be another yield call before `test_simple_preempt_start = 1;` and the start timestamp.

These have already been done recently and with these changes the tests pass on my hardware.

> * Remove all the `ZF_LOGD` calls from `test_simple_preempt_runner()` .

Do you want me to go ahead and make this change?

**Comment by Indanz** [comment]
> Do you want me to go ahead and make this change?

If it passes with the other changes, just leave it for now.
