### ISSUE TITLE
develop program for sel4

### ISSUE THREAD

**Issue by huxianglong** [seL4/sel4test#17]
Hi, I am trying to develop some programs on top of sel4. Let's say I've written some C programs under Linux with dependencies and compiled it into binary files. Those binary files would be pretty self-contained, i.e., not dependent on os,  Is it possible to port those binary files to sel4?

**Comment by kent-mcleod** [comment]
Hi @huxianglong,
This question would be better directed to the mailing list at https://sel4.systems/lists/listinfo/devel.

> Is it possible to port those binary files to sel4?

It depends on what your requirements are. If you don't require too many OS resources then it would be easier.  If you want to reuse the binary files without modification then your main option would be to load them in a Linux guest.  If you are happy to recompile from source and able to make modifications then using [Camkes](https://docs.sel4.systems/CAmkES/) may be sufficient.
