### ISSUE TITLE
Couldn't understand error in simulation

### ISSUE THREAD

**Issue by mrbahrani** [seL4/sel4test#19]
While running ninja command, it fails returning these
``
[1/62] Running C++ protocol buffer com...el4_projects_libs/libsel4rpc/rpc.proto
FAILED: apps/sel4test-driver/sel4_projects_libs/libsel4rpc/rpc.pb.c apps/sel4test-driver/sel4_projects_libs/libsel4rpc/rpc.pb.h 
cd /home/ali/Desktop/sel4-x86/build-x86/apps/sel4test-driver/sel4_projects_libs/libsel4rpc && PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND -I/home/ali/Desktop/sel4-x86/build-x86/nanopb/generator -I/home/ali/Desktop/sel4-x86/build-x86/nanopb/generator/proto -I/home/ali/Desktop/sel4-x86/build-x86/apps/sel4test-driver/sel4_projects_libs/libsel4rpc -I/home/ali/Desktop/sel4-x86/projects/sel4_projects_libs/libsel4rpc --plugin=protoc-gen-nanopb=/home/ali/Desktop/sel4-x86/build-x86/nanopb/generator/protoc-gen-nanopb --nanopb_out=:/home/ali/Desktop/sel4-x86/build-x86/apps/sel4test-driver/sel4_projects_libs/libsel4rpc /home/ali/Desktop/sel4-x86/projects/sel4_projects_libs/libsel4rpc/rpc.proto
/bin/sh: 1: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: not found
[3/62] Linking C executable kernel/kernel.elf
ninja: build stopped: subcommand failed.
``
I do not really understand what is missing :/

**Comment by mrbahrani** [comment]
I just realised that I hadn't installed protofub-compiler. You can do so by running
`` sudo sudo apt-get install protobuf-compiler ``
I hope it helps

**Comment by mrbahrani** [comment]
In case you need to know all the dependencies, check this link.
[Dependencies](https://docs.sel4.systems/HostDependencies
)

**Comment by kent-mcleod** [comment]
I also updated the README.md to refer to the getting started page so that it's clearer for people in the future.  Thanks for opening the issue!
