### ISSUE TITLE
image stops at "Jumping to kernel-image entry point..."

### ISSUE THREAD

**Issue by AKADiNG** [seL4/sel4test#22]
Hello everyone;

I am working on master branch and  trying to port sel4 to allwinnerR40 board.  When I tried to run the image on board, it stoped at "Jumping to kernel-image entry point..." when I run it on the board. Following is the printed messages:

sunxi#fatload mmc 0 0x40000000 sel4test_ding && bootelf 0x40000000
reading sel4test_ding
1568324 bytes read in 69 ms (21.7 MiB/s)
## Starting application at 0x40644000 ...

ELF-loader started on CPU: ARM Ltd. Cortex-A7 r0p5
  paddr=[40644000..407bc0a7]
No DTB passed in from boot loader.
Looking for DTB in CPIO archive...found at 40681880.
Loaded DTB from 40681880.
   paddr=[4002b000..40032fff]
ELF-loading image 'kernel'
  paddr=[40000000..4002afff]
  vaddr=[a0000000..a002afff]
  virt_entry=a0000000
ELF-loading image 'sel4test-driver'
  paddr=[40033000..40249fff]
  vaddr=[10000..226fff]
  virt_entry=164e8
Enabling MMU and paging
Jumping to kernel-image entry point...

Any suggestion is appreciated, thanks.

**Comment by yyshen** [comment]
Hello, 

Thanks for doing the port.

Could you show the result of the following command:

readelf -a kernel.elf

**Comment by nomadeel** [comment]
It could also be that release mode is turned on. Under release mode, the kernel doesn't have serial printing enabled so there's no serial output unless the serial device is configured in userland. You can check if release mode is turned on by running `ccmake` in the build directory and checking if the `RELEASE` flag is switched on.

**Comment by AKADiNG** [comment]
> It could also be that release mode is turned on. Under release mode, the kernel doesn't have serial printing enabled so there's no serial output unless the serial device is configured in userland. You can check if release mode is turned on by running `ccmake` in the build directory and checking if the `RELEASE` flag is switched on.

Thank you very much. Your advice works well. It finally print something after turn the "RELEASE" flag off. But there came another problem.

## Starting application at 0x40818000 ...

ELF-loader started on CPU: ARM Ltd. Cortex-A7 r0p5
  paddr=[40818000..40c60ca7]
No DTB passed in from boot loader.
Looking for DTB in CPIO archive...found at 408dad94.
Loaded DTB from 408dad94.
   paddr=[40037000..4003efff]
ELF-loading image 'kernel'
  paddr=[40000000..40036fff]
  vaddr=[a0000000..a0036fff]
  virt_entry=a0000000
ELF-loading image 'sel4test-driver'
  paddr=[4003f000..40425fff]
  vaddr=[10000..3f6fff]
  virt_entry=1d3e0
Enabling MMU and paging
Jumping to kernel-image entry point...

Bootstrapping kernel
Booting all finished, dropped to user space
Caught cap fault in send phase at address 0
while trying to handle:
vm fault on data at address 0x9f7fefff with status 0x805
in thread 0xffef7200 "sel4test-driver" at address 0x72a14
With stack:
0x2e3da0: 0xf
0x2e3da4: 0x1
0x2e3da8: 0x2e3db8
0x2e3dac: 0x2e3dd8
0x2e3db0: 0x1000
0x2e3db4: 0x2f4d20
0x2e3db8: 0x454
0x2e3dbc: 0x2c2100
0x2e3dc0: 0x9
0x2e3dc4: 0xa
0x2e3dc8: 0x453
0x2e3dcc: 0x20
0x2e3dd0: 0x2
0x2e3dd4: 0x0
0x2e3dd8: 0x1
0x2e3ddc: 0x455
... ...

Do you have any suggestions about this one ?

**Comment by AKADiNG** [comment]
> Hello,
> 
> Could you show the result of the following command:
> 
> readelf -a kernel.elf

@yyshen Thank you for your attention, @nomadeel's advice works well.

**Comment by nomadeel** [comment]
The thread seems to have tripped a page fault at an invalid address. It could be that the thread was trying to access invalid memory?

**Comment by AKADiNG** [comment]
@nomadeel  Succeed to run seL4test after I close the L1 data cache， but there are many efficiency lost in this way. The running time on board is  more than twice as long as in the qemu. So I think this is just a work around way, I should find out the real solution.

**Comment by yyshen** [comment]
> > It could also be that release mode is turned on. Under release mode, the kernel doesn't have serial printing enabled so there's no serial output unless the serial device is configured in userland. You can check if release mode is turned on by running `ccmake` in the build directory and checking if the `RELEASE` flag is switched on.
> 
> Thank you very much. Your advice works well. It finally print something after turn the "RELEASE" flag off. But there came another problem.
> 
> ## Starting application at 0x40818000 ...
> ELF-loader started on CPU: ARM Ltd. Cortex-A7 r0p5
> paddr=[40818000..40c60ca7]
> No DTB passed in from boot loader.
> Looking for DTB in CPIO archive...found at 408dad94.
> Loaded DTB from 408dad94.
> paddr=[40037000..4003efff]
> ELF-loading image 'kernel'
> paddr=[40000000..40036fff]
> vaddr=[a0000000..a0036fff]
> virt_entry=a0000000
> ELF-loading image 'sel4test-driver'
> paddr=[4003f000..40425fff]
> vaddr=[10000..3f6fff]
> virt_entry=1d3e0
> Enabling MMU and paging
> Jumping to kernel-image entry point...
> 
> Bootstrapping kernel
> Booting all finished, dropped to user space
> Caught cap fault in send phase at address 0
> while trying to handle:
> vm fault on data at address 0x9f7fefff with status 0x805
> in thread 0xffef7200 "sel4test-driver" at address 0x72a14
> With stack:
> 0x2e3da0: 0xf
> 0x2e3da4: 0x1
> 0x2e3da8: 0x2e3db8
> 0x2e3dac: 0x2e3dd8
> 0x2e3db0: 0x1000
> 0x2e3db4: 0x2f4d20
> 0x2e3db8: 0x454
> 0x2e3dbc: 0x2c2100
> 0x2e3dc0: 0x9
> 0x2e3dc4: 0xa
> 0x2e3dc8: 0x453
> 0x2e3dcc: 0x20
> 0x2e3dd0: 0x2
> 0x2e3dd4: 0x0
> 0x2e3dd8: 0x1
> 0x2e3ddc: 0x455
> ... ...
> 
> Do you have any suggestions about this one ?

@AKADiNG Can you attach the binary files: kernel.elf, sel4test-driver, and sel4test-tests?

**Comment by axel-h** [comment]
I suggest to close this issue, since there was no follow-up from @AKADiNG in the last 4 months.
