### ISSUE TITLE
when I build sel4 with sel4test, error occors that "UnicodeDecodeError: 'ascii' codec can't decode byte"

### ISSUE THREAD

**Issue by oska874** [seL4/sel4test#52]
I build sel4 with the guide from https://docs.sel4.systems/GettingStarted.html. but failed, error occors that:

```
[1/24] Generating from generated/plat_mode/machine/hardware.bf.pbf
FAILED: kernel/generated/plat_mode/machine/hardware_gen.h /workspace/s42/build-x86/kernel/generated/plat_mode/machine/hardware_gen.h
cd /workspace/s42/build-x86/kernel && python3 /workspace/s42/kernel/tools/bitfield_gen.py --prune /workspace/s42/build-x86/kernel/kernel_all_pp_prune.c /workspace/s42/build-x86/kernel/generated/plat_mode/machine/hardware.bf.pbf /workspace/s42/build-x86/kernel/generated/plat_mode/machine/hardware_gen.h
Traceback (most recent call last):
  File "/workspace/s42/kernel/tools/bitfield_gen.py", line 2772, in <module>
    string = f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 593714: ordinal not in range(128)
ninja: build stopped: subcommand failed.
```

My environment is ubuntu 18.04.

**Comment by axel-h** [comment]
Seems another 18.04 issue. Did you try the docker containers?
Is there any reason you have to use 18.04 or did you just pick this because the docs say so?

**Comment by GooTal** [comment]
I tried ubuntu18.04, but I need to install many packs and still got many errors. My friend used ubuntu 20.04 and he didn`t worry much about environment settings, pack dependencies. Now I am using 20.04 too, just found some small errors running sel4test like this.
![image](https://user-images.githubusercontent.com/40800103/156481983-5d437ab8-2ed3-43ed-9dfb-6ef1e74e3604.png)

**Comment by lsf37** [comment]
> I tried ubuntu18.04, but I need to install many packs and still got many errors. My friend used ubuntu 20.04 and he didn`t worry much about environment settings, pack dependencies. Now I am using 20.04 too, just found some small errors running sel4test like this.
> ![image](https://user-images.githubusercontent.com/40800103/156481983-5d437ab8-2ed3-43ed-9dfb-6ef1e74e3604.png)

The image you are showing is expected sel4test output before the test starts, i.e. it seems to be working correctly. How does the output continue?

**Comment by GooTal** [comment]
> > I tried ubuntu18.04, but I need to install many packs and still got many errors. My friend used ubuntu 20.04 and he didn`t worry much about environment settings, pack dependencies. Now I am using 20.04 too, just found some small errors running sel4test like this.
> > ![image](https://user-images.githubusercontent.com/40800103/156481983-5d437ab8-2ed3-43ed-9dfb-6ef1e74e3604.png)
> 
> The image you are showing is expected sel4test output before the test starts, i.e. it seems to be working correctly. How does the output continue?

Thank you for answering on https://github.com/seL4/sel4test-manifest/issues/18.

**Comment by axel-h** [comment]
I'm closing this, as all questions seem to be answered and https://github.com/seL4/seL4/pull/778 is merged.
