### ISSUE TITLE
sel4test builds are not reproducible

### ISSUE THREAD

**Issue by mokshasoft** [seL4/sel4test#8]
Not having reproducible builds may not be an error, but it is a very good property to have.

I ran the following script in a cleanly synced sel4test repo:
~/Repo/seL4/sel4test$ cat reproducible-builds.sh 
#!/bin/sh

for i in {1..10} ; do
    make mrproper > /dev/null 2>&1
    make bbone_black_release_xml_defconfig > /dev/null 2>&1
    make > /dev/null 2>&1
    sha1sum images/sel4test-driver-image-arm-am335x.bin
done
~/Repo/seL4/sel4test$ . reproducible-builds.sh 
7c83aa31c988bef3d34f0c03f0e71f0dd23c0087  images/sel4test-driver-image-arm-am335x.bin
34fecfcad3b984ba117633807bab98c5e8d1acaf  images/sel4test-driver-image-arm-am335x.bin
6c4ff733a495614adc37ab88a7b44156db576c06  images/sel4test-driver-image-arm-am335x.bin
c5ccd2967d41ab629d27343d243f0f4a05b38a68  images/sel4test-driver-image-arm-am335x.bin
84e750754afb9ffa54897d0f030bee262f67adab  images/sel4test-driver-image-arm-am335x.bin
9ffe2e35159475ea50d7a4db5dfdc71fc5479d68  images/sel4test-driver-image-arm-am335x.bin
a276e16cfa78b5a783d3831fa4e4d69a40d13568  images/sel4test-driver-image-arm-am335x.bin
0a753a04c7882cded39f85adad5924e6a76ea509  images/sel4test-driver-image-arm-am335x.bin
afda6bf5d398cc950a1ce1eb9b7431388ed0923d  images/sel4test-driver-image-arm-am335x.bin
c07bed74c7f6d04f72bcc01eb545da13707e1fc9  images/sel4test-driver-image-arm-am335x.bin

Diff:ing the binaries show that only a few bytes differ in a few places. If the root cause is in the sel4test git then this issue can be ignored, but currently I don't know if this comes from the sel4test git, the seL4_tools git or some other git involved in the build.

**Comment by AdrianDanis** [comment]
I was not aware that our builds were not deterministic and reproducible, thanks for discovering that. Off the top of my head I cannot guess what might be causing this, will look into this when we have time.

**Comment by OlympusMonds** [comment]
I know this is a very late addition to this conversation, but I did make sel4bench become reproducible here:
https://github.com/seL4/sel4bench/commit/a7a426f9dd5ca7de697533f32f63a8d475fc65b0
and have setup a regression test in our build server to make sure it stays that way (with the current build system and for the new CMake one when it comes in).

Sorting the source files (as per the commit) is important, but also stripping out any file metadata from the CPIO files is also vital for a truly reproducible build. There is a small tool to do this, found here: https://github.com/seL4/seL4_tools/blob/master/common-tool/cpio-strip.c
If you put the bin in your path somewhere, it should be applied to any CPIOs built.

**Comment by Smattr** [comment]
Since I wrote that tool, 2.12 of CPIO learned a flag [`--reproducible`](https://www.gnu.org/software/cpio/manual/html_node/Copy_002dpass-mode.html#Copy_002dpass-mode) to support the Debian reproducible builds project (though this functionality was previously available under other flags). It may be a simpler way to achieve the result you're after. It won't drop UID/GID, but they are a little more controllable.

**Comment by kent-mcleod** [comment]
This should be supported in the new build system. To verify you can run the following commands after a fresh checkout:
```bash
mkdir build && cd build
for i in {1..10} ; do 
rm -rf * > /dev/null 2>&1 \
&& ../init-build.sh -DAARCH32=TRUE -DPLATFORM=am335x > /dev/null 2>&1 \
&& ninja > /dev/null 2>&1 && sha1sum images/sel4test-driver-image-arm-am335x;
done

46e5c55b1a8fe385e059c56a50647ee92f25dac7  images/sel4test-driver-image-arm-am335x
46e5c55b1a8fe385e059c56a50647ee92f25dac7  images/sel4test-driver-image-arm-am335x
46e5c55b1a8fe385e059c56a50647ee92f25dac7  images/sel4test-driver-image-arm-am335x
....
```
